name: EssentialsDiscord
main: net.essentialsx.discord.EssentialsDiscord
# Note to developers: This next line cannot change, or the automatic versioning system will break.
version: ${full.version}
website: https://essentialsx.net/
description: Provides integration between Minecraft and Discord servers.
authors: [mdcfe]
depend: [Essentials]
softdepend: [EssentialsChat]
api-version: 1.13
